name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_TOKEN }}
  COHERE_API_TOKEN: ${{ secrets.COHERE_API_TOKEN }}
  ANTHROPIC_API_TOKEN: ${{ secrets.ANTHROPIC_API_TOKEN }}
  DOKU_URL: ${{ secrets.DOKU_URL }}
  DOKU_TOKEN: ${{ secrets.DOKU_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 21.x]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-action@v2

    - name: Setup Doku Stack
      run: docker-compose up -d
    
    - name: Sleep for 30 seconds
      run: sleep 30

    - name: Make API Request and Set DOKU_TOKEN
      run: |
        RESPONSE=$(curl --request POST \
          --url https://127.0.0.1:9044/api/keys \
          --header 'Authorization: ""' \
          --header 'Content-Type: application/json' \
          --data '{"name": "GITHUB"}' )
        MESSAGE=$(echo $RESPONSE | jq -r '.message')
        echo "DOKU_TOKEN=${MESSAGE}" >> $GITHUB_ENV

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: NPM CI
      run: npm ci

    - name: NPM build
      run: npm run build --if-present
    
    - name: NPM Test
      run: npm test
